### ISSUE TITLE
PermaVoice 1.12.2

### ISSUE THREAD

**Issue by HerXayah** [l3nnartt/PermaVoice-1.8#12]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
Permavoice for 1.12.2 back, da ich weiss das es mal existiert hat

**Additional context**
Since i use multiple Versions at the same time.

**Comment by l3nnartt** [comment]
Feel free to test [this](https://github.com/l3nnartt/PermaVoice-1.12/releases/tag/v1.0-PRE).
Since the VoiceChat does not work properly on Linux, I cannot test the whole thing well.

**Comment by PrincessAkira** [comment]
> Feel free to test [this](https://github.com/l3nnartt/PermaVoice-1.12/releases/tag/v1.0-PRE). Since the VoiceChat does not work properly on Linux, I cannot test the whole thing well.

has smth to do with UDP packets and their signature. Should be patchable by 3rd party somehow.

**Comment by l3nnartt** [comment]
Unfortunately not, afaik its the DDOS Protection of the voice chat server which rejects all connections from Linux

**Comment by PrincessAkira** [comment]
> Unfortunately not, afaik its the DDOS Protection of the voice chat server which rejects all connections from Linux

:wtf:

**Comment by l3nnartt** [comment]
Ive been able to test the whole thing and it seems to work, so I closing the issue.
If something does not work, you are welcome to create an issue in the 1.12 repo

**Comment by l3nnartt** [comment]
> has smth to do with UDP packets and their signature. Should be patchable by 3rd party somehow.

btw they fixed it! :D 🥳
